apiVersion: v1
kind: Service
metadata:
  name: connection-app
  namespace: app-nm
spec:
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 80  # Puerto del servicio
      targetPort: 3000  # Puerto al que redirige el servicio
  type: LoadBalancer  # Tipo de servicio (LoadBalancer en EKS para obtener un punto de conexión externo)

